modLoader = "javafml"
loaderVersion = "[40,)"
license = "MIT"

[[mods]]
modId = "tfcvesseltooltip"
version = "${file.jarVersion}"
displayName = "TFC Vessel Tooltip"
authors = "HermitOwO"
description = '''TFC Vessel Tooltip'''

[[dependencies.tfcvesseltooltip]]
modId = "forge"
mandatory = true
versionRange = "[40,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.tfcvesseltooltip]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2]"
ordering = "NONE"
side = "BOTH"

[[dependencies.tfcvesseltooltip]]
modId = "tfc"
mandatory = true
versionRange = "[2.2.0,)"
ordering = "NONE"
side = "BOTH"