modLoader = "javafml"
loaderVersion = "[47,)"
license = "MIT"

[[mods]]
modId = "tfcvesseltooltip"
version = "${file.jarVersion}"
displayName = "TFC Vessel Tooltip"
authors = "HermitOwO"
description = '''TFC Vessel Tooltip'''

[[dependencies.tfcvesseltooltip]]
modId = "forge"
mandatory = true
versionRange = "[47.1.3,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.tfcvesseltooltip]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20,1.21)"
ordering = "NONE"
side = "BOTH"

[[dependencies.tfcvesseltooltip]]
modId = "tfc"
mandatory = true
versionRange = "[3.0.0-beta,)"
ordering = "NONE"
side = "BOTH"